weibaohui/k8m

main.go, pkg/controller/dynamic/dynamic.go, pkg/controller/node/node.go, pkg/controller/pod/pod.go, pkg/service/node.go, pkg/service/node_watch.go, pkg/service/pod.go, pkg/service/pod_watch.go, pkg/service/service.go, ui/public/pages/cluster/node.json, ui/public/pages/ns/pod.json
=> Node label selector

README.md, README_en.md
- 优化 README.md 和 README_en.md 的格式和内容
- 添加项目启动和在线体验的详细说明
- 更新演示 DEMO 的访问信息
- 调整图片链接格式
=> docs(README): 增加docker-compose拉起的文档说明

.gitignore, main.go, pkg/controller/cm/cm.go, pkg/controller/svc/svc.go, pkg/flag/flag.go, ui/public/pages/ns/configmap.json
=> Configmap创建修改

pkg/models/config.go, pkg/models/migrate.go
调整Config结构体的字段默认值，并在初始化配置表时添加新字段EnableAI和LoginType，以增强配置的灵活性和功能性
=> refactor(models): 更新Config结构体和初始化配置表

pkg/models/config.go, pkg/models/migrate.go, pkg/service/config.go, ui/public/pages/admin/config/config.json
简化配置模型、服务和前端界面，移除不再使用的配置项，如调试模式、端口设置等，以提高代码的可维护性和清晰度。
=> refactor: 移除未使用的配置项和相关代码

pkg/middleware/cluster.go
将`EnsureSelectedClusterMiddleware`中的URL安全的Base64解码逻辑提取到`decodeUrlSafeBase64`函数中，以提高代码的可读性和可维护性。同时移除冗余的日志输出。
=> refactor: 将URL安全的Base64解码逻辑提取为独立函数

pkg/mcp/mcp_call.go
- 添加 clean函数对参数进行清理和格式化
- 去除空白字符、换行符和制表符
- 处理特殊情况下的参数值- 提高参数解析的准确性和可靠性
=> fix(mcp): 优化工具调用参数处理

main.go, pkg/constants/role.go, pkg/controller/admin/user/cluster_permission.go, pkg/controller/admin/user/user.go, pkg/controller/user/profile/profile.go, pkg/models/cluster_user_role.go, pkg/models/migrate.go, pkg/service/user.go, ui/public/pages/admin/cluster/cluster_all.json, ui/public/pages/admin/user/user.json, ui/public/pages/user/profile/my_clusters.json
=> 集群授权对用户组进行授权，授权后组内用户均有相应权限

go.mod, go.sum
在多个工具处理函数中添加了集群存在性检查，确保传入的集群名称有效。同时优化了错误提示信息，使其更加清晰和一致。
=> fix: 添加集群存在性检查并优化错误提示信息

ui/src/components/Amis/custom/K8sTextConditions.tsx, ui/src/store/conditions.ts
将K8sTextConditions组件中的反转条件列表状态管理从本地状态迁移到zustand store，以提高代码的可维护性和复用性
=> refactor(conditions): 将反转条件列表状态管理迁移到zustand,避免每个组件每次都访问

README.md, go.mod, go.sum, pkg/controller/node/node.go, pkg/controller/pod/pod.go, pkg/service/node.go, pkg/service/pod_watch.go, ui/public/pages/cluster/node.json, ui/public/pages/ns/pod.json
=> 增加页面Pod、命名空间、节点页面展示实时资源用量

pkg/controller/param/config.go, pkg/flag/flag.go, pkg/models/config.go, pkg/service/config.go, ui/public/pages/admin/config/config.json, ui/src/layout/index.tsx
在配置管理中添加产品名称字段，支持从前端设置并显示产品名称。包括模型、服务、控制器及前端界面的相关修改，确保产品名称可动态配置并展示。
=> feat(配置): 添加产品名称配置支持

ui/public/pages/gatewayapi/gateway.json, ui/public/pages/gatewayapi/gateway_class.json, ui/public/pages/gatewayapi/grpc_route.json, ui/public/pages/gatewayapi/http_route.json, ui/public/pages/gatewayapi/tcp_route.json, ui/public/pages/gatewayapi/tls_route.json, ui/public/pages/gatewayapi/udp_route.json, ui/src/components/Amis/custom/K8sTextConditions.tsx, ui/src/utils/utils.ts
=> 增加资源状态就绪情况展示

README.md
=> docs: 更新README.md中的安全提示

pkg/controller/pod/pod_xterm.go
为了避免多个goroutine同时写入WebSocket时发生竞争条件，引入写锁来保护写操作。封装了`safeWriteMessage`函数，确保每次写操作都是线程安全的。
=> fix(pod_xterm): 添加写锁确保WebSocket写操作的线程安全

go.mod, go.sum, main.go, pkg/controller/node/node.go, pkg/controller/pod/pod.go, ui/public/pages/cluster/node.json, ui/public/pages/ns/pod.json
新增Node、Pod资源用量展示页面，等同于kubectl top pods/nodes
=> 新增Node、Pod资源用量展示页面，等同于kubectl top pods/nodes

ui/public/pages/ns/daemonset.json, ui/public/pages/ns/deploy.json, ui/public/pages/ns/pod.json, ui/public/pages/ns/replicaset.json, ui/public/pages/ns/statefulset.json, ui/src/components/Amis/index.tsx, ui/src/pages/PodExec/index.tsx
简化终端按钮的实现方式，将原本的抽屉模式改为直接跳转到指定URL的方式，提升用户体验并减少代码复杂度
=> refactor(ui): 将终端按钮从抽屉模式改为URL跳转模式

mcp_start.go
- 在 actFn 函数中添加了日志记录语句，用于记录 CallToolRequest 的详细信息
- 使用 klog.V(6) 控制日志级别，仅在调试模式下输出
- 通过 utils.ToJSON 函数将请求对象序列化为 JSON 格式，便于阅读和分析
=> feat:增加工具调用请求的日志记录

main.go, pkg/middleware/auth.go, ui/src/components/Amis/fetcher.ts, ui/src/routes/index.tsx
在main.go中添加了AuthMiddleware以进行登录校验。更新了ui/src/routes/index.tsx中的默认路由路径，将其重定向到用户集群页面。修改了ui/src/components/Amis/fetcher.ts中的错误处理逻辑，将错误提示从error改为info。在pkg/middleware/auth.go中增加了对特定路径的跳过登录检测逻辑，以提高用户体验和安全性。
=> feat(middleware): 添加AuthMiddleware并更新路由和错误处理

pkg/controller/pod/pod_forward.go
在StartPortForward函数中添加了对podPort参数的整数验证，以确保其有效性。如果podPort不是有效的整数，将返回错误信息，避免后续处理中的潜在问题。
=> fix(pod_forward): 添加podPort的整数验证

go.mod, go.sum, mcp_start.go, pkg/middleware/cache.go
=> 新增大模型保存yaml为模板功能

main.go, mcp_start.go, pkg/cb/cb.go, pkg/middleware/auth.go, ui/public/pages/user/profile/api_keys.json, ui/public/pages/user/profile/mcp_keys.json
MCP 访问路径兼容动态路径/mcp/k8m/xxxx/sse格式，适用于不支持设置Header的MCP客户端
=> MCP 访问路径兼容动态路径/mcp/k8m/xxxx/sse格式，适用于不支持设置Header的MCP客户端

pkg/controller/admin/mcp/mcp_tools.go
在ToolsList函数中，添加了根据名称筛选工具列表的功能，确保返回的列表仅包含指定名称的工具
=> fix(mcp): 根据名称筛选工具列表

pkg/flag/flag.go, pkg/models/config.go, pkg/service/chat.go, pkg/service/config.go, pkg/service/service.go, ui/public/pages/admin/config/config.json
将MaxIterations字段从chatService结构体中移除，改为从Config中获取，以提高配置的集中性和可维护性。同时在config.json中添加了对应的UI配置项。
=> refactor(chat): 将MaxIterations从chatService移至Config

pkg/controller/chat/chat.go, pkg/controller/chat/chat_websocket.go, pkg/service/chat.go, ui/src/components/Amis/custom/WebSocketMarkdownViewer.tsx
Fix chat history 修复大模型对话记录跟其他单轮解释互相影响的问题
=> Fix chat history 修复大模型对话记录跟其他单轮解释互相影响的问题

Makefile, go.mod, go.sum, pkg/controller/node/xterm.go, ui/public/pages/user/cluster/cluster_user.json
=> Fix shell error

ui/src/components/Amis/custom/LogView/SSELogDisplay.tsx
清理代码中未使用的状态变量filterResult，简化组件状态管理
=> refactor(SSELogDisplay): 移除未使用的filterResult状态变量

ui/public/pages/ns/svc.json
=> feat(ui): 在服务页面添加外部地址显示功能

ui/public/pages/istio/VirtualService.json
重构故障注入模板以支持多HTTP路由配置，并添加颜色区分不同类型的故障
=> fix(istio): 修复虚拟服务故障注入显示格式问题

ui/public/pages/istio/DestinationRule.json, ui/public/pages/istio/Gateway.json, ui/public/pages/istio/ServiceEntry.json
=> 完善Istio DR、SE、GW等资源展示内容

pkg/controller/login/login.go, pkg/controller/sso/oidc.go, pkg/controller/sso/sso.go, pkg/service/user.go, ui/public/pages/admin/config/sso_config.json
=> 对齐OIDC groups 配置

pkg/controller/admin/config/condition.go, pkg/controller/admin/mcp/mcp_tools.go
=> fix: 修正数据库更新字段从'Disabled'到'enabled'

go.mod, go.sum
=> fix:apply  yaml 时报缺少必要参数问题

pkg/controller/helm/helm_release.go, pkg/helm/helm_cmd.go, ui/public/pages/helm/release.json
在helm命令中添加--debug参数以输出调试日志
添加获取release安装日志的API接口和前端展示页面
=> feat(helm): 添加获取release安装日志功能

pkg/models/ai_model_config.go, pkg/models/api_key.go, pkg/models/cluster_user_role.go, pkg/models/condition_reverse.go, pkg/models/config.go, pkg/models/custom_template.go, pkg/models/helm_chart.go, pkg/models/helm_release.go, pkg/models/helm_repository.go, pkg/models/kube_config.go, pkg/models/ldap_config.go, pkg/models/mcp_key.go, pkg/models/mcp_log.go, pkg/models/mcp_server.go, pkg/models/mcp_tool.go, pkg/models/menu.go, pkg/models/operation_log.go, pkg/models/shell_log.go, pkg/models/sso_config.go, pkg/models/user.go, pkg/models/user_group.go
统一为所有模型的CreatedAt字段添加gorm:"<-:create"标签，防止该字段被意外更新
=> refactor(models): 为CreatedAt字段添加gorm:"<-:create"标签

pkg/comm/utils/random.go, pkg/comm/utils/random_test.go
将随机数生成器从 math/rand 替换为 crypto/rand，以生成更安全的随机数
在生成失败时返回默认值，确保函数始终有返回值
=> perf(utils): 使用 crypto/rand 替换 math/rand 以提高安全性

pkg/controller/param/version.go, ui/public/pages/about/about.json
- 控制器接口返回中加入数据库类型字段
- 关于页面新增数据库类型的只读文本展示
=> feat(param): 添加数据库类型信息显示

pkg/controller/param/cluster.go, pkg/service/clusters.go
- 修正ClusterTableList中InCluster和AWSEKS的逻辑判断，避免条件错误
- 增强GetCertificateExpiry函数的健壮性，增加多层空值和异常检查
- 添加kubeConfig为空、config解析失败、context和authInfo缺失等多种异常日志
- 防止证书解析失败或空值导致的程序错误
- 移除RegisterCluster函数末尾多余空行，提高代码整洁度
=> fix(cluster): 修复集群证书过期时间获取的健壮性问题

go.mod, go.sum
=> chore(deps): 更新kom依赖版本到v0.2.64

ui/src/layout/index.module.scss, ui/src/styles/global.scss
adjust layout and table styles for improved responsiveness
=> style: adjust layout and table styles for improved responsiveness

pkg/controller/admin/cluster/cluster.go, pkg/controller/admin/cluster/kubeconfig.go, pkg/controller/param/cluster.go, pkg/models/kube_config.go, ui/public/pages/admin/cluster/cluster_all.json
=> 新增使用token方式纳管集群
