weibaohui/k8m

.dockerignore, .github/release-drafter.yml, .github/workflows/build-docker-image.yml, .github/workflows/build-release.yml, .github/workflows/release-drafter.yml, Dockerfile, Dockerfile.action, Makefile
需要在仓库增加两个秘钥：
```
ALIHUB_TOKEN
DOCKERHUB_TOKEN
```
第二：需要修改docker仓库的几个信息：
然后提交之后，会自动构建docker镜像，每次提交，或者pr都会自动构建release的草稿，感觉需要发布版本，可以点击编辑release草稿，没问题之后，点击发布，自动触发流水线，将对应版本的二进制发布到release中。
目前还存在的问题：
1. docker镜像目前只构建了linux-amd64，比较奇怪arm64构建会卡住，提了个issue，后续关注一下。见：https://github.com/docker/build-push-action/issues/1348
2. 目前二进制构建使用的makefile，属于串行，因此整体构建下来要十八分钟，但压缩效果比较理想。我也换了：https://github.com/wangyoucao577/go-release-action 构建，看了下这个仓库使用的upx是v4.0的，压缩之后，会比makefile打出来的体积大一倍。故而暂时放弃。但这种方式是并发构建，整体打完大概五分钟左右。后续看看完全自定义构建命令，然后并发构建，应该会提升很多。
3. github action强大归强大，调试还是比较费劲儿的。
=> feat: 配置自动构建release与镜像的action

pkg/flag/flag.go, pkg/models/config.go, pkg/service/config.go, ui/public/pages/admin/config/config.json
在配置服务、模型、前端页面和命令行标志中添加了AI功能开关配置，默认开启。这使得管理员能够通过UI界面或命令行参数控制AI功能的启用状态。
=> feat: 添加AI功能开关配置

.github/workflows/build-release.yml, Makefile
- 重命名 GitHub Actions 中的 job 为 build-release
- 注释掉 Makefile 中不常用的平台编译选项
- 为 macOS 平台增加专门的 UPX 压缩参数
=> ci(build): 优化 Release 构建流程和 UPX 压缩设置

ui/src/pages/Login/index.tsx
移除Login页面中未使用的GithubOutlined图标，以简化代码并减少不必要的依赖
=> refactor(Login): 移除未使用的GithubOutlined图标

mcp_start.go, pkg/mcp/mcp_log.go, pkg/service/user.go
在MCP工具调用时，添加错误和成功日志记录功能，方便追踪工具执行情况。同时，在用户服务中增加临时管理员角色支持，当配置启用时，特定用户将被赋予平台管理员角色。
=> feat: 添加MCP工具调用日志记录和临时管理员角色支持

ui/public/pages/user/profile/mcp_keys.json
更新了MCP密钥页面的使用说明，增加了通过NodePort或网关方式访问时的注意事项。同时，修改了SSE链接的格式，明确指定了端口号为3619，以提高访问的准确性。
=> docs(user/profile): 更新MCP密钥页面的使用说明和SSE链接格式

go.mod, go.sum, pkg/mcp/mcp_call.go, pkg/mcp/mcp_host.go
将 `client.SSEMCPClient` 类型统一更新为 `client.Client`，同时将 `github.com/spf13/cast` 依赖从 v1.7.0 升级到 v1.7.1，并将 `github.com/weibaohui/mcp-go` 依赖从 v0.0.1 升级到 v0.0.5
=> refactor(client): 更新客户端类型并升级依赖

main.go, pkg/controller/dynamic/crd_status.go, ui/src/components/Sidebar/menu.tsx
在`crd_status.go`中添加了`CRDStatus`函数，用于检查集群是否支持网关API。在`main.go`中注册了新的API路由`/crd/status`。在`menu.tsx`中增加了对网关API支持状态的获取，并根据状态动态显示或隐藏网关API相关菜单项
=> feat(网关API): 添加网关API支持状态检查及动态菜单显示

pkg/service/mcp_host.go
在生成JWT令牌时，增加了错误处理逻辑，避免因令牌生成失败导致程序崩溃。如果生成失败，返回包含服务器名称和错误信息的错误消息。
=> fix(mcp_host): 处理生成JWT令牌时的错误

main.go, pkg/controller/admin/user/cluster_permission.go, ui/public/pages/admin/cluster/cluster_all.json
新增`ListClusterNamespaceListByClusterID`接口，用于获取集群下的命名空间列表。优化了命名空间选择功能，将原有的`input-array`替换为`transfer`组件，提升用户体验。
=> feat(admin): 新增集群命名空间列表接口并优化命名空间选择功能

internal/dao/conn.go
为了避免SQLite数据库的并发问题，设置最大打开连接数为1，确保每次只有一个连接访问数据库，从而提高稳定性和性能。
=> perf(dao): 设置SQLite最大打开连接数为1

ui/public/pages/admin/cluster/cluster_all.json, ui/public/pages/ns/daemonset.json, ui/public/pages/ns/deploy.json, ui/public/pages/ns/replicaset.json, ui/public/pages/ns/statefulset.json, ui/public/pages/user/profile/mcp_keys.json
为了简化集群管理页面的用户界面，移除了命名空间选择功能及其相关代码。此功能在当前使用场景中不再需要，减少了不必要的复杂性。
=> refactor(ui): 移除集群管理页面中的命名空间选择功能

pkg/middleware/cache.go
将max-age的值从字符串转换改为使用strconv.Itoa进行转换，以确保正确设置缓存时间
=> fix: 修复Cache-Control头中的max-age值转换错误

go.mod, go.sum, pkg/service/user.go
修改GetClusterRole方法，在查询用户集群角色时同时包含用户本身及其所属用户组的角色。原实现仅查询用户本身的角色，导致用户组权限无法生效。
主要变更：
- 将用户组名称加入查询条件
- 更新相关注释说明
=> fix(service): 修复获取用户集群角色时未包含用户组角色问题

ui/src/components/Amis/custom/XTerm.tsx
修改文件ui/src/components/Amis/custom/XTerm.tsx 53行
const ws = new WebSocket(`ws://${location.host}` + url);
在早期的浏览器实现中，WebSocket 的支持并不完善。低版本的 Chrome 可能没有完全实现对相对路径的支持，或者出于兼容性考虑，只支持绝对路径。随着浏览器版本的更新，WebSocket 的实现逐渐完善，但规范仍然要求使用绝对路径，以保持一致性和安全性。
=> fix(XTerm): 修复工作负载/部署 容器组控制台功能在Linux系统浏览器上打开报错的问题

main.go, pkg/cb/cb.go, pkg/comm/utils/amis/gin.go, pkg/comm/utils/slice.go, pkg/controller/admin/user/cluster_permission.go, pkg/controller/ns/ns.go, pkg/models/cluster_user_role.go, ui/public/pages/admin/cluster/cluster_all.json, ui/public/pages/user/profile/my_clusters.json
白名单命名空间：置空表示不限制，可访问该集群下所有的命名空间。如果填写了，那么用户就只能访问指定的命名空间了。
黑名单命名空间：置空表示不限制，如果填写了，那么用户将不能访问该命名空间。黑名单可否定白名单。黑名单权限最高。
=> 新增黑白名单命名空间限制。

pkg/cb/cb.go, pkg/controller/admin/config/condition.go, pkg/controller/admin/mcp/mcp_tools.go, pkg/controller/admin/user/user.go, pkg/controller/login/login.go, pkg/models/user.go, pkg/service/user.go, ui/public/pages/admin/user/user.json
实现用户禁用功能，包括：
- 在用户模型中添加disabled字段
- 添加用户状态快速保存接口
- 在登录和MCP密钥验证时检查用户禁用状态
- 更新错误提示信息更明确
- 添加前端用户列表的禁用开关和快速保存功能
=> feat(用户管理): 添加用户禁用功能及相关接口

ui/public/pages/openkruise/container_recreate_request.json, ui/public/pages/openkruise/imagepulljob.json, ui/public/pages/openkruise/uniteddeployment.json, ui/public/pages/openkruise/workloadspread.json, ui/src/components/Sidebar/menu.tsx
添加工作负载分布菜单项到侧边栏，并创建对应的页面配置文件，支持查看和管理 WorkloadSpread 资源
=> feat(ui): 添加工作负载分布菜单项和页面配置

ui/public/pages/openkruise/PodUnavailableBudget.json, ui/public/pages/openkruise/ResourceDistribution.json, ui/public/pages/openkruise/persistentpodstate.json, ui/public/pages/openkruise/podprobemarker.json, ui/src/components/Sidebar/menu.tsx
支持对如下OpenKruise资源管理：
advancedcronjobs.apps.kruise.io                
broadcastjobs.apps.kruise.io                   
clonesets.apps.kruise.io                       
containerrecreaterequests.apps.kruise.io       
daemonsets.apps.kruise.io                      
imagelistpulljobs.apps.kruise.io               
imagepulljobs.apps.kruise.io                   
nodeimages.apps.kruise.io                      
nodepodprobes.apps.kruise.io                   
persistentpodstates.apps.kruise.io             
podprobemarkers.apps.kruise.io                 
podunavailablebudgets.policy.kruise.io         
resourcedistributions.apps.kruise.io           
sidecarsets.apps.kruise.io                     
statefulsets.apps.kruise.io                    
uniteddeployments.apps.kruise.io …
=> OpenKruise支持

Dockerfile.action
- 修改 apk 安装命令，新增 aws-cli 包
- 优化镜像构建过程，保持其他依赖不变
- 确保所有必需工具权限正确设置
=> chore(docker): 在镜像中添加 aws-cli 依赖

pkg/controller/param/user.go
当用户是平台管理员时，直接返回空菜单数据，跳过后续集群和权限检查逻辑
=> feat(controller): 为平台管理员添加特殊菜单权限处理
